version: '3.9'
services:
  wxchat:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai # 时区
    ports:
      - 80:80
    stdin_open: true # docker run -i
    tty: true  # docker run -t
    privileged: true #允许容器修改
    volumes:
      - /home/wxchat/logs:/home/nodeapp/logs/